name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:


jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Run tests
        run: make testci
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: test-results/**/*.xml
          check_name: Test Result (Python ${{matrix.python-version}})
      - name: Conclusion
        run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"
