name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:


jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Look por style errors
        run: pflake8
      - name: Check por import style
        run: isort --profile=black --check --diff dundie tests integration
      - name: Look por auto format errors
        run: black --check --diff dundie tests integration

  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Run tests
        run: pytest -v --forked --junitxml=test-results/test_result.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: test-results/**/*.xml
          check_name: Test Result (Python ${{matrix.python-version}})
      - name: Conclusion
        run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"
